---
version: "2.0"

services:
  akash:
    image: ghcr.io/certikfoundation/shentu:latest
    env:
      # - STATE_SYNC=1
      - SEEDS_URL=https://raw.githubusercontent.com/certikfoundation/testnet/master/yulei-2/seeds.txt
      - SYNC_URL=https://raw.githubusercontent.com/certikfoundation/testnet/master/yulei-2/rpc.txt
      - GENESIS_URL=https://raw.githubusercontent.com/certikfoundation/testnet/master/yulei-2/genesis.json
      - ENABLE_ID_SERVER=true
      # - CERTIK_PRUNING=custom
      # - CERTIK_PRUNING_INTERVAL=10
      # - CERTIK_PRUNING_KEEP_EVERY=50
      # - CERTIK_PRUNING_KEEP_RECENT=10
      # - CERTIK_STATE_SYNC_SNAPSHOT_INTERVAL=50
      # - CERTIK_STATE_SYNC_KEEP_RECENT=10
      # - CERTIK_SEED_MODE=true
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 9090
        to:
          - global: true

profiles:
  compute:
    certik:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 32Gi
  placement:
    dcloud:
      attributes:
        host: akash
      pricing:
        akash: 
          denom: uakt
          amount: 200

deployment:
  akash:
    dcloud:
      profile: certik
      count: 1
