name: publish
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.CR_USER }}" --password-stdin
          docker build . --tag ghcr.io/jim380/certik-on-akash:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/jim380/certik-on-akash:${GITHUB_REF#refs/tags/}
